on:
  release:
    types: [published]

name: Publish

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Set git env
        run: |
          echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Make envfile
        run: |
          cat > .env
          echo "STORYBOOK_VERSION=${{ env.TAG_NAME }}" >> .env
          echo "STORYBOOK_V_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> .env
          echo "$(<.env)"

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 20.11

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install depends
        run: pnpm install --ignore-scripts

      - name: Build Theme
        run: pnpm build

      - name: Publish Theme
        run: pnpm publish --no-git-check
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build StoryBook
        run: pnpm build-sb

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy to S3
        run: aws s3 sync ./storybook-static/ s3://${{ vars.S3_BUCKET }} --delete
