on:
  release:
    types: [published]

name: Publish

jobs:
  sb-build-and-deploy:
    name: StoryBook Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Login Docker
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: Set git env
        run: |
          echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Make envfile
        run: |
          cat > .env
          echo "STORYBOOK_VERSION=${{ env.TAG_NAME }}" >> .env
          echo "STORYBOOK_V_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> .env
          echo "$(<.env)"

      - name: Build and Push Docker Image
        run: |
          docker build . -t ${{ secrets.AZURE_LOGIN_SERVER }}/npm-tema-story-book:${{ env.TAG_NAME }}
          docker push ${{ secrets.AZURE_LOGIN_SERVER }}/npm-tema-story-book:${{ env.TAG_NAME }}

  theme-build-and-publish:
    name: Theme Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 18.16

      - name: Install NPM Login
        run: yarn global add npm-cli-login

      - name: NPM Login
        run: NPM_USER=${{ vars.NPM_USER }} NPM_PASS=${{ secrets.NPM_PASS }} NPM_EMAIL=any@any.com NPM_REGISTRY=${{ secrets.NPM_URL }} npm-cli-login

      - name: Build Theme
        run: |
          yarn --ignore-scripts
          yarn publish --no-git-tag-version
